### ISSUE TITLE
A more robust way of sending data

### ISSUE THREAD

**Issue by book** [jhthorsen/mojo-tftpd#10]
I don't think `Mojo::TFTPd` is vulnerable to the [Sorcerer's Apprentice Syndrome](https://en.wikipedia.org/wiki/Sorcerer's_Apprentice_Syndrome), because it will only resend a data packet once.

However, `Mojo::TFTPd`'s current way of deal with the data transfer is suboptimal:
- because `retries` is never reset for a connection, that means there will only be a single retry for the whole connection
- because the `DATA` packets (except the first one) are only sent in response of an `ACK`, the server will sit waiting until the `inactive_timeout` is reached (and drop the connection) if a client `ACK` packet is lost
- each `DATA` packet is effectively only sent once, over a lossly protocol (UDP), so long lasting connections (think files of 100Mb or more) are very likely to lose packets at some point and be dropped because of the above

Instead of a `retries` count, I think `Mojo::TFTPd` should have a `retry_timeout`. So without any `ACK` received before the `retry_timeout`, the server would send the last `DATA` packet again. Because the `DATA` is also sent in reply to any `ACK` packet, the server should wait some time (e.g. `retry_timeout`) before re-sending any `DATA` packet (I've seen duplicated `ACK` in the wild) to avoid falling prey to the Sorcerer's Apprentice Syndrome. This is actually the [recommended solution](https://en.wikipedia.org/wiki/Sorcerer's_Apprentice_Syndrome#Solution).

I will soon submit a pull request on top of `feature/custom-class` that will implement the above proposal in `send_data`.

**Comment by jhthorsen** [comment]
I believe this issue is closed by the merge above.

Thank you @book :smile_cat:
