### ISSUE TITLE
Support for reading the data sent in a reponse to a rrq request in an event-driven manner

### ISSUE THREAD

**Issue by book** [jhthorsen/mojo-tftpd#7]
I'm writing a TFTP-HTTP proxy, that will basically use HTTP to fetch the "file content" whenever the requested filename starts with `http://`. Right now, I have to fetch the content in a blocking manner because Mojo::TFTPd expects the `rrq` handler to return a filehandle. (I actually return a IO::String object with the response body.)

Would it be possible to return a callback (or something else) so that `send_data` would get (and buffer, and possibly wait and retry if nothing's available yet) the next chunk of data using the callback?

Thanks.

**Comment by jhthorsen** [comment]
I believe this issue is resolved.

Thank you @book :smile:
